### ISSUE TITLE
Initial Roadmap for Implementation

### ISSUE THREAD

**Issue by tanjera** [tanjera/asah.nomogram#1]
Overarching functionality to implement:
- [ ] Ability to calculate nurses' actions based on input and decision points:
  - [ ] Below / At / Above glucose target?
  - [ ] Stop/Proceed based on K+ levels?
  - [ ] Sanity checking of inputs

Specific functionality to implement:
- [ ] Above target range (Appendix B: p. 1) for DKA && HHS
  - [ ] If gtt is continuing (not new!) && glucose testing is q1hr: 
    - [ ] Adjust dosing multiplier based on Table 1
    - [ ] Adjust dose rate based on p. 4-5
    - [ ] **Instruct**: new dose rate and/or multiplier
  - [ ] If gtt is continuing (not new!) && glucose testing is q2hr/q4hr: 
    - [ ] Check glucose in 1 hour; further instructions based on re-check:
      - [ ] If in target range, re-check glucose as previously
      - [ ] If above target range, adjust dose rate using p. 4-5
        - [ ] **Instruct**: glucose check q1hr; new dose rate
- [ ] In target range (Appendix B: p. 2) for DKA && HHS
  - [ ] Adjust dose rate based on p. 4-5
  - [ ] **Instruct**: fluids w/ D5 (e.g. D5/0.45%)
- [ ] Below target range (Appendix B: p. 2) for DKA only
  - [ ] Instructions based on p. 2 of multiplier versus glucose reading (3 x 3 contingency table)
- [ ] Below target range (Appendix B: p. 2) for HHS only
  - [ ] Instructions based on p. 3 of glucose reading (3 x 1 contingency table)
